### ISSUE TITLE
Having issues with running the workshop code

### ISSUE THREAD

**Issue by erin5116** [RadiotherapyAI/unet-workshop#1]
I finally got some time to go through the workshop code in detail and found that it runs smoothly until model training, which then fails and the error code is not very informative.
`Epoch 1/50
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-137-74e60c5c98b6> in <cell line: 1>()
----> 1 history = model.fit(
      2     datasets["training"],
      3     epochs=50,
      4     validation_data=datasets["validation"],
      5     callbacks=[callback],

1 frames
/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py in error_handler(*args, **kwargs)
    120             # To get the full stack trace, call:
    121             # `keras.config.disable_traceback_filtering()`
--> 122             raise e.with_traceback(filtered_tb) from None
    123         finally:
    124             del filtered_tb

ValueError: as_list() is not defined on an unknown TensorShape.`

Any idea why that is?

**Comment by SimonBiggs** [comment]
Oof, no idea.  I haven't touched tensorflow for a very long time

**Comment by SimonBiggs** [comment]
Throw it into the sonnet model on Claude.ai? Maybe Claude will know?

**Comment by erin5116** [comment]
After some more learning and debugging, I found that somehow the data elements lost their shape (still finding out why/where). But the temp fix is
`def set_shape(image, label):

  image.set_shape((64,64, 1))
  label.set_shape((64,64,3))

  return image, label`

and using `dataset = dataset.map(set_shape)` after `dataset = dataset.map(load)` in the create_datasets function

**Comment by SimonBiggs** [comment]
Did you want to make a pull request?
